FROM apache/airflow:2.8.1
USER root
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir \
    scikit-learn==1.2.2 \
    pandas==2.0.3 \
    numpy==1.23.5 \
    joblib==1.2.0 \
    requests
RUN touch /opt/airflow/airflow-worker.pid && chmod 644 /opt/airflow/airflow-worker.pid
